spring:
  application:
    name: trade-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ramesh-singh-20/trade-common-config

server:
  port: 9196

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

